### ISSUE TITLE
[question] can be used to tween camera from current position/settings to another pre setted position?

### ISSUE THREAD

**Issue by moebiussurfing** [nariakiiwatani/ofxKeyframeTween#2]
thanks for sharing this @nariakiiwatani ,

I am looking at the example how you chain some keys. 
But can we pre-set some keys and jump between them in "one tween jump" without running around all the keys sequentially?

Maybe this is possible using some internal classes? or it goes out of the intention of the addon?

I would like something like:
1. set 5 camera positions/settings
2. jump to position # 2 in some desired time duration
3. jump to position # 5...

**Comment by moebiussurfing** [comment]
I tried this approach, but it's not working and I don't' know if could be a better way:

```.cpp
//.h
ofCamera camera;

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
	if (key == '1')
	{
		camera_.clear();
		ofCamera cam;
		ofVec3f lookat;

		cam.setPosition(camera.getPosition());
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(0, { cam, lookat }, OF_EASE_CUBIC_IN);

		cam.setPosition(ofVec3f(50, 500, 1000));
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(1, {cam, lookat}, OF_EASE_CUBIC_IN);
	}
	if (key == '2')
	{
		camera_.clear();
		ofCamera cam;
		ofVec3f lookat;

		cam.setPosition(camera.getPosition());
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(0, {cam, lookat}, OF_EASE_CUBIC_IN);

		cam.setPosition(ofVec3f(50, 500, -1000));
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(1, {cam, lookat}, OF_EASE_CUBIC_IN);
	}
}
```

**Comment by nariakiiwatani** [comment]
Hi, I think your approach is the best and nothing is wrong as far as I notice.
I tried with your code and got good result.
What's happening on yours?

```
#include "ofApp.h"
#include "ofxKeyframeTween.h"
#include "ofxTweenTypeInterpolation.h"

ofxKeyframeTween<ofx::tweentype::interpolate::camera::Orbit> camera_;
ofCamera camera;
float timer = 0;

//--------------------------------------------------------------
void ofApp::update(){
	timer += ofGetLastFrameTime();
}

//--------------------------------------------------------------
void ofApp::draw(){
	camera_.getValue(ofClamp(timer,0,1)).apply(camera);
	camera.begin();
	ofDrawBox(100);
	camera.end();
}

//--------------------------------------------------------------
void ofApp::keyPressed(int key){
	if (key == '1')
	{
		camera_.clear();
		ofCamera cam;
		ofVec3f lookat;
		
		cam.setPosition(camera.getPosition());
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(0, { cam, lookat }, OF_EASE_CUBIC_IN);
		
		cam.setPosition(ofVec3f(50, 500, 1000));
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(1, {cam, lookat}, OF_EASE_CUBIC_IN);
	}
	if (key == '2')
	{
		camera_.clear();
		ofCamera cam;
		ofVec3f lookat;
		
		cam.setPosition(camera.getPosition());
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(0, {cam, lookat}, OF_EASE_CUBIC_IN);
		
		cam.setPosition(ofVec3f(50, 500, -1000));
		lookat.set(0, 0, 0);
		cam.lookAt(lookat);
		camera_.addKeyFrame(1, {cam, lookat}, OF_EASE_CUBIC_IN);
	}
	timer = 0;
}
```

**Comment by moebiussurfing** [comment]
nice! I am happy that the addon can be used to do this. 
(I was stuck using https://github.com/stefang/ofxSphereCam because of the gimbal problems.)

Using your code it crashes when pressing 1/2 keys. (That's what happened on my code too)

I am on VS2017 / Windows10 / main OF branch

![Capture](https://user-images.githubusercontent.com/2106149/82739529-acabc100-9d16-11ea-8cf5-b9f03eab0ddf.PNG)

![Capture2](https://user-images.githubusercontent.com/2106149/82739533-afa6b180-9d16-11ea-8690-a6fa8a14daf6.PNG)

**Comment by moebiussurfing** [comment]
it's working on macOS here too, so it could be some Windows error

**Comment by moebiussurfing** [comment]
I think that I found the problem. It crashes when using Debug mode. 
On Release mode, it seems to work.

(I tried on 0.10 too to check if could be something about ofVec3f vs glm::vec3, but it works the same.)

**Comment by nariakiiwatani** [comment]
Thank you for the additional information and sorry for being late.

Seems fixed by last commit. f40db99e1ca7fc1440380c3e5dc7582902c52a80

I somehow have passed a vector of length 1 for ofVec3f tween.
Please check it out!
